def printPlayersCurrentStatus(p1L, p1R, p2L, p2R):
    print("-----------------*********-----------------")
    print("-----------------*********-----------------")
    print("         PLAYER'S CURRENT STATUS")
    print(" ")
    print("PLAYER 1 :: " + str(p1L) +"  " + str(p1R))
    print("PLAYER 2 :: " + str(p2L) +"  " + str(p2R))
    print(" ")
    print("-----------------*********-----------------")
    print("-----------------*********-----------------")