N = int(input())
i = 1
n1 = (N+1)/2
n2 = (n1-1)
while i <= n1:
    spaces=1
    while spaces <= n1 - i:
        print(" ", end="")
        spaces+=1
    star=1
    while star <= (2*i) - 1:
        print("*", end="")
        star+=1
    print()
    i = i + 1
i = n2
x = 1
while x <= n2:
    spaces=1
    while spaces <= n2 - i + 1:
        print(" ", end="")
        spaces+=1
    star=1
    while star <= (2*i) - 1:
        print("*", end="")
        star+=1
    print()
    x = x + 1
    i = i - 1